---

- name: postfix is present
  package:
    name: postfix
    state: present

- name: postfix is configured
  notify: reload postfix
  template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf

- name: postfix is running
  service:
    name: postfix
    state: started
  
